spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.kamal.notificationservice.event.PaymentResultEvent
        spring.json.use.type.headers: false